version: '3.9'
services:
  server:
    build: .
    ports:
      - '8002:8002'

    volumes:
      - .:/twodatabase

    depends_on:
      - dev-database
    networks:
      - project

  dev-database:
    image: postgres
    ports:
      - '5439:5432'
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=test
    networks:
      - project

  database:
    image: postgres
    ports:
      - '5438:5432'
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=testIntegeration
    networks:
      - project

networks:
  project:
